export type Project = { slug: string; title: string; year: string; category: string; role: string; support: string; summary: string; image: string; heroImage: string; gallery: string[]; wide?: boolean; video?: string; videoNote?: string };

export const projects: Project[] = [
  { slug: 'convencao-lg-2025', title: 'Convenção LG', year: '2025', category: 'Design, audiovisual & branding', role: 'Criação de marca, peças gráficas e direção de arte', support: 'Impressos, digital, motion e audiovisual', summary: 'Identidade visual completa para a convenção de fim de ano da LG lugar de gente — do sistema de marca e das apresentações aos materiais de palco e vídeos cinematográficos.', image: '/images/convention/hero.jpg', heroImage: '/images/convention/hero.jpg', gallery: ['/images/convention/mockup.jpg', '/images/convention/stage.jpg', '/images/convention/presentation.jpg', '/images/convention/application.jpg'], wide: true, video: 'https://www.youtube-nocookie.com/embed/QrJVfi0FfZQ' },
  { slug: 'lg-40-anos', title: '40 anos LG lugar de gente', year: '2025', category: 'Branding, audiovisual & comunicação interna', role: 'Direção criativa, identidade visual, edição e sonoplastia', support: 'Digital, audiovisual e identidade para evento', summary: 'Uma identidade comemorativa desdobrada em comunicação interna, série de entrevistas e um documentário sobre a história da companhia.', image: '/images/lg40/listing.jpg', heroImage: '/images/lg40/banner.jpg', gallery: ['/images/lg40/listing.jpg'], video: 'https://www.youtube-nocookie.com/embed/14jYNLDDKbE', videoNote: 'Versão alternativa do documentário. A produção integral tem 19 minutos e contém material confidencial.' },
  { slug: 'continentes-seguros', title: 'Continentes Seguros', year: '2025—26', category: 'Design instrucional, branding & audiovisual', role: 'Direção criativa, identidade, storytelling e e-learning', support: 'Digital, Articulate Storyline, audiovisual e artigos', summary: 'Programa de conscientização sobre segurança e privacidade estruturado como uma experiência narrativa e gamificada, acompanhando sua evolução entre duas edições.', image: '/images/spi/2026-hero.jpg', heroImage: '/images/spi/2025-interface.jpg', gallery: ['/images/spi/2025-story.jpg', '/images/spi/2025-detail.jpg', '/images/spi/2026-banner.jpg', '/images/spi/2026-social.jpg'] },
  { slug: 'deck-de-cultura', title: 'Deck de Cultura', year: '2026', category: 'Branding, design gráfico & comunicação interna', role: 'Direção criativa, identidade visual e criação de ícones', support: 'Digital — PPTX e PDF', summary: 'Sistema visual para apresentar missão, linha do tempo e pilares da cultura organizacional, incluindo cinco marcas exclusivas para os valores corporativos.', image: '/images/culture/cover.jpg', heroImage: '/images/culture/cover.jpg', gallery: ['/images/culture/values.jpg', '/images/culture/value-1.jpg', '/images/culture/value-2.jpg', '/images/culture/timeline.jpg'] },
  { slug: 'lola-frita', title: 'Lola Frita', year: '2019—23', category: 'Direção editorial, design editorial & branding', role: 'Direção criativa e editorial, design e produção editorial', support: 'Impresso, digital e eventos', summary: 'Quatro anos de direção de um selo editorial independente: identidade, comunicação e o ciclo de criação e produção de mais de 20 livros, zines e plaquetes.', image: '/images/lola/fair.jpg', heroImage: '/images/lola/fair.jpg', gallery: ['/images/lola/fofocas.jpeg', '/images/lola/mapa.jpeg', '/images/lola/chame.jpeg', '/images/lola/horse.jpeg', '/images/lola/casa.jpeg', '/images/lola/kuarup.jpeg', '/images/lola/fair-detail.jpg'], wide: true },
];

export function getProject(slug: string) { return projects.find((project) => project.slug === slug); }
